Asp_Sample/Areas/Admin/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Context;
using DataLayer.Entity.Group;
using Microsoft.AspNetCore.Authorization;
using Microsoft.CodeAnalysis.CSharp;

namespace Asp_Sample.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class GroupsController : Controller
    {
        private readonly AppDbContext _context;

        public GroupsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Groups
        public async Task<IActionResult> Index()
        {
            return View(await _context.Groups.ToListAsync());
        }

        // GET: Admin/Groups/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // GET: Admin/Groups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupId,GroupTitle")] Group @group)
        {
            if (ModelState.IsValid)
            {
                @group.GroupId = Guid.NewGuid();
                _context.Add(@group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }

        // GET: Admin/Groups/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups.FindAsync(id);
            if (@group == null)
            {
                return NotFound();
            }
            return View(@group);
        }

        // POST: Admin/Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("GroupId,GroupTitle")] Group @group)
        {
            if (id != @group.GroupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await GroupExists(@group.GroupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }

        // GET: Admin/Groups/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // POST: Admin/Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var @group = await _context.Groups.FindAsync(id);
            _context.Groups.Remove(@group);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> GroupExists(Guid id)
        {
            return await  _context.Groups.AnyAsync(e => e.GroupId == id);
        }
    }
}

Asp_Sample/Areas/Admin/Controllers/UserGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Context;
using DataLayer.Entity.Group;
using Microsoft.AspNetCore.Authorization;

namespace Asp_Sample.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class UserGroupsController : Controller
    {
        private readonly AppDbContext _context;

        public UserGroupsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/UserGroups
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.UserGroups.Include(u => u.Group).Include(u => u.User);
            return View(await appDbContext.ToListAsync());
        }

        public async Task<IActionResult> GroupUsers(Guid groupId)
        {
            var appDbContext = _context.UserGroups
                .Include(u => u.Group)
                .Include(u => u.User)
                .Where(u => u.GroupId == groupId);
            var name = await _context.Groups.Where(c => c.GroupId == groupId).Select(c => c.GroupTitle).FirstOrDefaultAsync();
            if(name == null)
            {
                name = "بدون نام";
            }
            ViewData["GroupId"] = groupId;
            ViewData["Name"] = name;
            return View(await appDbContext.ToListAsync());
        }

        // GET: Admin/UserGroups/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userGroup = await _context.UserGroups
                .Include(u => u.Group)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.UserGroupId == id);
            if (userGroup == null)
            {
                return NotFound();
            }

            return View(userGroup);
        }

        // GET: Admin/UserGroups/Create
        public IActionResult Create()
        {
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupTitle");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName");
            return View();
        }

        public IActionResult AddUser(Guid groupId)
        {
            ViewData["GroupId"] = new SelectList(_context.Groups.Where(g => g.GroupId == groupId), "GroupId", "GroupTitle");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName");
            return View("Create");
        }

        // POST: Admin/UserGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserGroupId,GroupId,UserId")] UserGroup userGroup)
        {
            if (ModelState.IsValid)
            {
                userGroup.UserGroupId = Guid.NewGuid();
                var flag = await _context.UserGroups
                    .Where(c => c.UserId == userGroup.UserId && c.GroupId == userGroup.GroupId).AnyAsync();
                if(!flag)
                {
                    await _context.AddAsync(userGroup);
                    await _context.SaveChangesAsync();
                }
                
                return RedirectToAction(nameof(Index), "Groups");
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupTitle", userGroup.GroupId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName", userGroup.UserId);
            return View(userGroup);
        }

        // GET: Admin/UserGroups/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userGroup = await _context.UserGroups.FindAsync(id);
            if (userGroup == null)
            {
                return NotFound();
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupTitle", userGroup.GroupId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName", userGroup.UserId);
            return View(userGroup);
        }

        // POST: Admin/UserGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("UserGroupId,GroupId,UserId")] UserGroup userGroup)
        {
            if (id != userGroup.UserGroupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userGroup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await UserGroupExists(userGroup.UserGroupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Groups");
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupTitle", userGroup.GroupId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "UserName", userGroup.UserId);
            return View(userGroup);
        }

        // GET: Admin/UserGroups/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userGroup = await _context.UserGroups
                .Include(u => u.Group)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.UserGroupId == id);
            if (userGroup == null)
            {
                return NotFound();
            }

            return View(userGroup);
        }

        // POST: Admin/UserGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var userGroup = await _context.UserGroups.FindAsync(id);
            _context.UserGroups.Remove(userGroup);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Groups");
        }

        private async Task<bool> UserGroupExists(Guid id)
        {
            return await  _context.UserGroups.AnyAsync(e => e.UserGroupId == id);
        }
    }
}

Asp_Sample/Areas/Admin/Controllers/VoteGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer.Context;
using DataLayer.Entity.Group;
using Microsoft.AspNetCore.Authorization;

namespace Asp_Sample.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin" )]
    [Area("Admin")]
    public class VoteGroupsController : Controller
    {
        private readonly AppDbContext _context;

        public VoteGroupsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/VoteGroups
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.VoteGroups.Include(v => v.Group).Include(v => v.Vote);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Admin/VoteGroups/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voteGroup = await _context.VoteGroups
                .Include(v => v.Group)
                .Include(v => v.Vote)
                .FirstOrDefaultAsync(m => m.VoteGroupId == id);
            if (voteGroup == null)
            {
                return NotFound();
            }

            return View(voteGroup);
        }

        // GET: Admin/VoteGroups/Create
        public IActionResult Create()
        {
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupTitle");
            ViewData["VoteId"] = new SelectList(_context.Votes, "VoteId", "VoteName");
            return View();
        }

        // POST: Admin/VoteGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VoteGroupId,GroupId,VoteId")] VoteGroup voteGroup)
        {
            if (ModelState.IsValid)
            {
                voteGroup.VoteGroupId = Guid.NewGuid();
                _context.Add(voteGroup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupTitle", voteGroup.GroupId);
            ViewData["VoteId"] = new SelectList(_context.Votes, "VoteId", "VoteName", voteGroup.VoteId);
            return View(voteGroup);
        }

        // GET: Admin/VoteGroups/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voteGroup = await _context.VoteGroups.FindAsync(id);
            if (voteGroup == null)
            {
                return NotFound();
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupTitle", voteGroup.GroupId);
            ViewData["VoteId"] = new SelectList(_context.Votes, "VoteId", "VoteName", voteGroup.VoteId);
            return View(voteGroup);
        }

        // POST: Admin/VoteGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("VoteGroupId,GroupId,VoteId")] VoteGroup voteGroup)
        {
            if (id != voteGroup.VoteGroupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(voteGroup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await VoteGroupExists(voteGroup.VoteGroupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupTitle", voteGroup.GroupId);
            ViewData["VoteId"] = new SelectList(_context.Votes, "VoteId", "VoteName", voteGroup.VoteId);
            return View(voteGroup);
        }

        // GET: Admin/VoteGroups/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voteGroup = await _context.VoteGroups
                .Include(v => v.Group)
                .Include(v => v.Vote)
                .FirstOrDefaultAsync(m => m.VoteGroupId == id);
            if (voteGroup == null)
            {
                return NotFound();
            }

            return View(voteGroup);
        }

        // POST: Admin/VoteGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var voteGroup = await _context.VoteGroups.FindAsync(id);
            _context.VoteGroups.Remove(voteGroup);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> VoteGroupExists(Guid id)
        {
            return await  _context.VoteGroups.AnyAsync(e => e.VoteGroupId == id);
        }
    }
}

Asp_Sample/Areas/Admin/Views/Groups/Create.cshtml
@model DataLayer.Entity.Group.Group

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GroupTitle" class="control-label"></label>
                <input asp-for="GroupTitle" class="form-control" />
                <span asp-validation-for="GroupTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Asp_Sample/Areas/Admin/Views/Groups/Delete.cshtml
@model DataLayer.Entity.Group.Group

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupTitle)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GroupId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Asp_Sample/Areas/Admin/Views/Groups/Details.cshtml
@model DataLayer.Entity.Group.Group

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Group</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupTitle)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.GroupId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Asp_Sample/Areas/Admin/Views/Groups/Edit.cshtml
@model DataLayer.Entity.Group.Group

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GroupId" />
            <div class="form-group">
                <label asp-for="GroupTitle" class="control-label"></label>
                <input asp-for="GroupTitle" class="form-control" />
                <span asp-validation-for="GroupTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Asp_Sample/Areas/Admin/Views/Groups/Index.cshtml
@model IEnumerable<DataLayer.Entity.Group.Group>

@{
    ViewData["Title"] = "Index";
}


<div class="text-center">
    <p>
        <a class="btn btn-outline-primary" asp-action="Create">ایجاد گروه جدید</a>
        <a class="btn btn-outline-primary" asp-controller="UserGroups" asp-action="Index">مدیریت اعضای گروه ها</a>
        <a class="btn btn-outline-primary" asp-controller="VoteGroups" asp-action="Index">مدیریت گروه های سوالات</a>
    </p>
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupTitle)
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupTitle)
                </td>
                <td>
                    <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@item.GroupId">ویرایش</a> |
                    <a class="btn btn-outline-primary" asp-controller="UserGroups" asp-action="AddUser" asp-route-groupId="@item.GroupId">افزودن عضو جدید</a> |

                    @*<a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.GroupId">Details</a> |*@
                    <a class="btn btn-outline-info" asp-controller="UserGroups" asp-action="GroupUsers" asp-route-groupId="@item.GroupId">مشاهده اعضا</a> |
                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.GroupId">حذف</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>